{
 "title": "Cassandra CDC to Pulsar Dashboard by ORAMAD",
 "description": "https://github.com/Sarma1807/Cassandra_CDC-to-Pulsar",
 "tags": [
  "Apache Cassandra",
  "Apache Pulsar"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pulsar_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pulsar_version_info, cluster)"
    }
   },
   {
    "name": "pulsar_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(pulsar_producers_count{cluster=~\"$pulsar_cluster\"}, namespace)"
    }
   },
   {
    "name": "pulsar_topic",
    "label": "Topic",
    "query": {
     "query": "label_values(pulsar_producers_count{cluster=~\"$pulsar_cluster\", namespace=~\"$pulsar_namespace\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pulsar Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pulsar_version_info{cluster=\"$pulsar_cluster\"}"
    }
   ]
  },
  { "title": "$pulsar_cluster : Pulsar Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "pulsar_cluster" },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_connection_created_total_count{cluster=\"$pulsar_cluster\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_active_connections{cluster=\"$pulsar_cluster\"}"
    }
   ]
  },
  {
   "title": "Closed Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_connection_closed_total_count{cluster=\"$pulsar_cluster\"}"
    }
   ]
  },
  {
   "title": "Successful Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_connection_create_success_count{cluster=\"$pulsar_cluster\"}"
    }
   ]
  },
  {
   "title": "Failed Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_connection_create_fail_count{cluster=\"$pulsar_cluster\"}"
    }
   ]
  },
  { "title": "$pulsar_topic : Topic Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Producers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_producers_count{cluster=\"$pulsar_cluster\",namespace=\"$pulsar_namespace\",topic=\"$pulsar_topic\"}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_consumers_count{cluster=\"$pulsar_cluster\",namespace=\"$pulsar_namespace\",topic=\"$pulsar_topic\"}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_subscriptions_count{cluster=\"$pulsar_cluster\",namespace=\"$pulsar_namespace\",topic=\"$pulsar_topic\"}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_in_messages_total{cluster=\"$pulsar_cluster\",namespace=\"$pulsar_namespace\",topic=\"$pulsar_topic\"}"
    }
   ]
  },
  {
   "title": "Size (MB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_in_bytes_total{cluster=\"$pulsar_cluster\",namespace=\"$pulsar_namespace\",topic=\"$pulsar_topic\"}"
    }
   ]
  },
  { "title": "Author Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 13 },
   "options": {
    "content": "<h2> Cassandra CDC to Pulsar Dashboard by ORAMAD </h2>\n<br>\n<h5>\nSoftware Used : <br>\nPrometheus : Collects and Stores Metrics in Time Series Database <br>\nGrafana : Visualization Tool for Metrics Served by Prometheus <br>\nMetrics : Apache Pulsar Publishes Metrics <br>\n</h5>\n<h6> Version 0.1 (April 2022)</h6>\n<br>\n<h4> <a href=\"https://github.com/Sarma1807/Cassandra_CDC-to-Pulsar\" target=\"_blank\">Visit GitHub Page For More Details</a> </h4>\n"
   }
  }
 ]
}